=== RumbaCodeColors/Ejercicio_1_Jorge/ejercicio_1.dtd
<!ELEMENT asuntos (asunto)>
<!ELEMENT asunto (finicio,ffin,estado,cliente,procurador+)>
<!ATTLIST estado tipo (tramite | finalizado | archivado) #REQUIRED>
<!ELEMENT finicio (#PCDATA)>
<!ATTLIST asunto id_expediente ID #REQUIRED>
<!ELEMENT id_expediente (#PCDATA)>
<!ELEMENT ffin (#PCDATA)>
<!ELEMENT estado (#PCDATA)>
<!ELEMENT cliente (Nombre,Direccion,dni)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Direccion (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT procurador (Nombre,Direccion,dni)>

=== RumbaCodeColors/Ejercicio_1_Jorge/ejercicio_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE asuntos SYSTEM "ejercicio_1.dtd">
<asuntos>
    <asunto id_expediente="A123">
        <finicio>2025-06-11</finicio>
        <ffin>2025-12-11</ffin>
        <estado tipo="archivado"></estado>
        <cliente>
            <Nombre>Jorge Perez</Nombre>
            <Direccion>C/ Val 27</Direccion>
            <dni>12345678A</dni>
        </cliente>
        <procurador>
            <Nombre>Raul Ramirez</Nombre>
            <Direccion>C/ Argentina 6</Direccion>
            <dni>12345678B</dni>
        </procurador>
     
    </asunto>  
</asuntos>
